import assert from 'node:assert/strict';
import { saveJSON } from '../src/game.js';
import { familyPlaceForPuzzle, notePlayedFamilyPlace, skipFamilyPlace, resetSkippedFamilyPlaces } from '../src/social.js';
const store = new Map();
globalThis.localStorage = { getItem: (key) => store.get(key) ?? null, setItem: (key, value) => store.set(key, value) };
const champaign = { name: 'Champaign', by: 'Marc' };
saveJSON('social.places', [champaign]);
assert.equal(familyPlaceForPuzzle(100, 'Mara').name, 'Champaign');
notePlayedFamilyPlace('Champaign', 100);
assert.equal(familyPlaceForPuzzle(101, 'Mara'), null, 'legacy played history prevents tomorrow repetition');
assert.equal(familyPlaceForPuzzle(129, 'Mara'), null);
assert.equal(familyPlaceForPuzzle(130, 'Mara').name, 'Champaign');
skipFamilyPlace(' CHAMPAIGN ');
assert.equal(familyPlaceForPuzzle(500, 'Mara'), null, 'skip persists beyond cooldown');
saveJSON('social.places', [champaign, { name: 'Paris', by: 'Marc' }]);
assert.equal(familyPlaceForPuzzle(501, 'Mara').name, 'Paris', 'new eligible family places still appear');
assert.equal(familyPlaceForPuzzle(501, 'Marc'), null, 'authors do not get their own questions');
resetSkippedFamilyPlaces();
saveJSON('social.places', [champaign]);
assert.equal(familyPlaceForPuzzle(501, 'Mara').name, 'Champaign');
console.log('PASS family skip persistence, legacy cooldown, empty eligible pack, new questions and restore');
