// Explicitly classified point/site landmarks in the curated game catalogue.
// Precision is measured against the game's designated destination coordinate.
export const LANDMARK_NAMES = new Set([
  "Red Square, Moscow",
  "Eiffel Tower, Paris",
  "Colosseum, Rome",
  "Big Ben, London",
  "Sagrada Família, Barcelona",
  "Brandenburg Gate, Berlin",
  "Neuschwanstein Castle",
  "Stonehenge",
  "Prague Castle",
  "Edinburgh Castle",
  "Transylvania — Bran Castle",
  "Kyiv — Saint Sophia Cathedral",
  "Taj Mahal, Agra",
  "Burj Khalifa, Dubai",
  "Kyoto — Fushimi Inari Shrine",
  "Bali — Uluwatu Temple",
  "Seoul — Gyeongbokgung Palace",
  "Bangkok — Grand Palace",
  "Kuala Lumpur — Petronas Towers",
  "Statue of Liberty, New York",
  "Golden Gate Bridge",
  "Teotihuacan Pyramids",
  "Toronto — CN Tower",
  "Christ the Redeemer, Rio",
  "Pyramids of Giza",
  "Luxor — Karnak Temple",
  "Djenné Great Mosque, Mali",
  "Sydney Opera House",
  "Leaning Tower of Pisa",
  "Palace of Versailles",
  "Vienna — Schönbrunn Palace",
  "Osaka Castle, Japan",
  "Auschwitz-Birkenau Memorial, Poland",
  "Nova Festival Memorial, Re'im",
  "Terezín Memorial",
  "Babyn Yar Memorial, Kyiv",
  "Øresund Bridge",
  "Lake Geneva — Chillon Castle",
  "Chesapeake Bay Bridge",
  "Bergen-Belsen Memorial",
  "Łódź Ghetto Memorial",
  "Minsk — Yama Memorial",
  "Devils Tower, Wyoming",
  "Canterbury Cathedral",
  "Stirling Castle, Scotland",
  "Cologne Cathedral",
  "Lucerne — Chapel Bridge",
  "Melk Abbey, Austria",
  "Trakai Island Castle, Lithuania",
  "Split — Diocletian’s Palace",
  "Bucharest — Palace of the Parliament",
  "Meroë Pyramids, Sudan",
  "Yamoussoukro Basilica",
  "Cape Coast Castle, Ghana",
  "Abu Dhabi — Sheikh Zayed Mosque",
  "Kuwait City — Kuwait Towers",
  "Tehran — Milad Tower",
  "Turkestan — Yasawi Mausoleum",
  "Amritsar — Golden Temple",
  "Khajuraho Temples, India",
  "Kolkata — Victoria Memorial",
  "Lahore — Badshahi Mosque",
  "Islamabad — Faisal Mosque",
  "Kandy — Temple of the Tooth",
  "Lhasa — Potala Palace",
  "Hiroshima Peace Memorial",
  "Himeji Castle, Japan",
  "Nikko — Toshogu Shrine",
  "Chiang Rai — White Temple",
  "Da Nang — Golden Bridge",
  "Yangon — Shwedagon Pagoda",
  "Bristol — Clifton Bridge",
  "Newcastle — Angel of the North",
  "Malbork Castle, Poland",
  "Garni Temple, Armenia",
  "Mysore Palace, India",
  "Madurai — Meenakshi Temple",
  "Matsumoto Castle, Japan",
  "Conwy Castle, Wales",
  "Agrigento — Valley of the Temples",
  "Peleș Castle — Sinaia",
  "Mir Castle, Belarus",
  "Cholula Pyramid, Mexico",
  "Qufu — Confucius Temple",
  "Acropolis of Athens",
  "Angkor Wat, Cambodia",
  "Mount Rushmore",
  "Borobudur, Indonesia",
  "Mont-Saint-Michel",
  "Budapest Parliament",
  "Verona Arena",
  "Rock of Cashel, Ireland",
  "Great Wall of China (Badaling)",
  "Tokyo — Shibuya Crossing",
  "Petra, Jordan",
  "Marina Bay Sands, Singapore",
  "Istanbul — Hagia Sophia",
  "Beijing — Forbidden City",
  "Kathmandu — Boudhanath Stupa",
  "Jaipur — Hawa Mahal",
  "Samarkand — Registan",
  "Taipei 101",
  "Chichén Itzá, Mexico",
  "Yellowstone — Old Faithful",
  "Hollywood Sign, Los Angeles",
  "Chicago — The Bean",
  "Washington — The Capitol",
  "Seattle — Space Needle",
  "St. Louis — Gateway Arch",
  "Machu Picchu, Peru",
  "Buenos Aires — Obelisco",
  "Lalibela Rock Churches",
  "Aswan — Abu Simbel",
  "Granada — Alhambra"
]);
export function isLandmark(target) {
  return !target.isFamily && !target.isNews && LANDMARK_NAMES.has(target.name);
}
export function landmarkBonus(target, distanceKm) {
  if (!isLandmark(target) || !Number.isFinite(distanceKm) || distanceKm < 0) return 0;
  return distanceKm <= 0.025 ? 25 : distanceKm <= 0.1 ? 10 : 0;
}
export function precisionTotal(rounds) {
  return rounds.reduce((sum, round) => sum + (round.precisionBonus || 0), 0);
}

export function precisionMessage(target, bonus) {
  if (!isLandmark(target)) return '';
  return bonus ? `+${bonus} landmark precision` : 'No precision bonus — get within 100 m for +10 or 25 m for +25.';
}
