// MarcTap curated location database.
// name: the clue shown to the player. sub: optional secondary hint (shown for harder picks).
// country must match the Natural Earth NAME property so country-floor scoring works.
// diff: 1 = famous/easy, 2 = medium, 3 = tricky. fact: shown after the round.

export const LOCATIONS = [
  // ================= EUROPE =================
  { name: 'Eiffel Tower, Paris', lat: 48.8584, lng: 2.2945, country: 'France', continent: 'Europe', diff: 1, fact: 'Built for the 1889 World\'s Fair, it was meant to stand for only 20 years.' },
  { name: 'Colosseum, Rome', lat: 41.8902, lng: 12.4922, country: 'Italy', continent: 'Europe', diff: 1, fact: 'Up to 50,000 spectators could file in and out through its 80 entrances.' },
  { name: 'Big Ben, London', lat: 51.5007, lng: -0.1246, country: 'United Kingdom', continent: 'Europe', diff: 1, fact: 'Big Ben is technically the bell — the tower is officially the Elizabeth Tower.' },
  { name: 'Sagrada Família, Barcelona', lat: 41.4036, lng: 2.1744, country: 'Spain', continent: 'Europe', diff: 1, fact: 'Under construction since 1882 and still not finished.' },
  { name: 'Brandenburg Gate, Berlin', lat: 52.5163, lng: 13.3777, country: 'Germany', continent: 'Europe', diff: 1, fact: 'Once stranded in the death strip of the Berlin Wall, now a symbol of reunification.' },
  { name: 'Acropolis of Athens', lat: 37.9715, lng: 23.7267, country: 'Greece', continent: 'Europe', diff: 1, fact: 'The Parthenon atop it has survived wars, explosions, and 2,400 years of weather.' },
  { name: 'Amsterdam Canal Ring', lat: 52.3676, lng: 4.9041, country: 'Netherlands', continent: 'Europe', diff: 1, fact: 'The city has more than 1,200 bridges spanning its 17th-century canals.' },
  { name: 'Venice Grand Canal', lat: 45.4408, lng: 12.3155, country: 'Italy', continent: 'Europe', diff: 1, fact: 'The city stands on millions of wooden piles driven into the lagoon mud.' },
  { name: 'Neuschwanstein Castle', lat: 47.5576, lng: 10.7498, country: 'Germany', continent: 'Europe', diff: 2, fact: 'King Ludwig II\'s fairytale castle inspired Disneyland\'s Sleeping Beauty Castle.' },
  { name: 'Stonehenge', lat: 51.1789, lng: -1.8262, country: 'United Kingdom', continent: 'Europe', diff: 2, fact: 'Some of its stones were hauled about 250 km from the hills of Wales.' },
  { name: 'Mont-Saint-Michel', lat: 48.636, lng: -1.5114, country: 'France', continent: 'Europe', diff: 2, fact: 'At high tide the abbey becomes an island; at low tide you can walk across the sand.' },
  { name: 'Santorini, Greece', lat: 36.3932, lng: 25.4615, country: 'Greece', continent: 'Europe', diff: 2, fact: 'Its cliff-top villages sit on the rim of a volcano that erupted around 1600 BC.' },
  { name: 'Dubrovnik Old Town', lat: 42.6407, lng: 18.1077, country: 'Croatia', continent: 'Europe', diff: 2, fact: 'Its intact medieval walls made it a filming location for King\'s Landing.' },
  { name: 'Prague Castle', lat: 50.0911, lng: 14.4016, country: 'Czechia', continent: 'Europe', diff: 2, fact: 'By area it is one of the largest castle complexes in the world.' },
  { name: 'Red Square, Moscow', lat: 55.7539, lng: 37.6208, country: 'Russia', continent: 'Europe', diff: 1, fact: 'St. Basil\'s swirling domes were built for Ivan the Terrible in the 1550s.' },
  { name: 'Hallstatt, Austria', lat: 47.5622, lng: 13.6493, country: 'Austria', continent: 'Europe', diff: 2, fact: 'This lakeside village sits above salt mines worked for 7,000 years.' },
  { name: 'Cliffs of Moher', lat: 52.9715, lng: -9.4309, country: 'Ireland', continent: 'Europe', diff: 2, fact: 'The Atlantic cliffs rise 214 metres straight out of the sea.' },
  { name: 'Edinburgh Castle', lat: 55.9486, lng: -3.1999, country: 'United Kingdom', continent: 'Europe', diff: 2, fact: 'It sits on the plug of an extinct volcano above the Scottish capital.' },
  { name: 'Geirangerfjord, Norway', lat: 62.1049, lng: 7.0952, country: 'Norway', continent: 'Europe', diff: 2, fact: 'Waterfalls called the Seven Sisters spill over its kilometre-high walls.' },
  { name: 'Blue Lagoon, Iceland', lat: 63.8804, lng: -22.4495, country: 'Iceland', continent: 'Europe', diff: 2, fact: 'The milky-blue water is warm runoff from a geothermal power plant.' },
  { name: 'Lisbon, Portugal', lat: 38.7223, lng: -9.1393, country: 'Portugal', continent: 'Europe', diff: 1, fact: 'Europe\'s westernmost capital rebuilt itself after a huge earthquake in 1755.' },
  { name: 'Matterhorn, Zermatt', lat: 45.9766, lng: 7.6585, country: 'Switzerland', continent: 'Europe', diff: 2, fact: 'Its four faces point almost exactly north, south, east and west.' },
  { name: 'Bruges, Belgium', lat: 51.2093, lng: 3.2247, country: 'Belgium', continent: 'Europe', diff: 2, fact: 'Medieval canals earned it the nickname "Venice of the North".' },
  { name: 'Copenhagen Nyhavn', lat: 55.6797, lng: 12.5912, country: 'Denmark', continent: 'Europe', diff: 2, fact: 'Hans Christian Andersen wrote fairy tales while living along this harbor.' },
  { name: 'Stockholm Old Town', lat: 59.3251, lng: 18.0711, country: 'Sweden', continent: 'Europe', diff: 2, fact: 'The city spreads across 14 islands connected by 57 bridges.' },
  { name: 'Budapest Parliament', lat: 47.5071, lng: 19.0458, country: 'Hungary', continent: 'Europe', diff: 2, fact: 'One of the world\'s largest parliament buildings, mirrored nightly in the Danube.' },
  { name: 'Krakow Main Square', lat: 50.0619, lng: 19.9369, country: 'Poland', continent: 'Europe', diff: 2, fact: 'Europe\'s largest medieval town square hosts a trumpeter who plays every hour.' },
  { name: 'Plitvice Lakes', lat: 44.8654, lng: 15.582, country: 'Croatia', continent: 'Europe', diff: 3, fact: 'Sixteen terraced lakes spill into each other through travertine waterfalls.' },
  { name: 'Meteora Monasteries', lat: 39.7217, lng: 21.6306, country: 'Greece', continent: 'Europe', diff: 3, fact: 'Monks once reached these cliff-top monasteries by rope ladders and nets.' },
  { name: 'Transylvania — Bran Castle', lat: 45.5149, lng: 25.3672, country: 'Romania', continent: 'Europe', diff: 3, fact: 'Marketed as "Dracula\'s Castle", though Bram Stoker never visited Romania.' },
  { name: 'Faroe Islands', lat: 62.0, lng: -6.7833, country: 'Denmark', continent: 'Europe', diff: 3, fact: 'These 18 North Atlantic islands have more sheep than people.' },
  { name: 'Gibraltar', lat: 36.1408, lng: -5.3536, country: 'United Kingdom', continent: 'Europe', diff: 3, fact: 'Home to Europe\'s only wild monkeys, the Barbary macaques.' },
  { name: 'Malta — Valletta', lat: 35.8989, lng: 14.5146, country: 'Malta', continent: 'Europe', diff: 3, fact: 'The fortified capital was built by the Knights of St. John after a 1565 siege.' },
  { name: 'Lake Bled, Slovenia', lat: 46.3625, lng: 14.0936, country: 'Slovenia', continent: 'Europe', diff: 3, fact: 'A tiny island church in the lake is reached by wooden boats called pletnas.' },
  { name: 'Kyiv — Saint Sophia Cathedral', lat: 50.4529, lng: 30.5145, country: 'Ukraine', continent: 'Europe', diff: 2, fact: 'Its 11th-century mosaics have survived nearly a thousand years.' },
  { name: 'Helsinki, Finland', lat: 60.1699, lng: 24.9384, country: 'Finland', continent: 'Europe', diff: 2, fact: 'A church here, Temppeliaukio, is carved directly into solid rock.' },
  { name: 'Vilnius, Lithuania', lat: 54.6872, lng: 25.2797, country: 'Lithuania', continent: 'Europe', diff: 3, fact: 'Its old town is one of the largest surviving medieval quarters in Europe.' },
  { name: 'Andorra la Vella', lat: 42.5063, lng: 1.5218, country: 'Andorra', continent: 'Europe', diff: 3, fact: 'The highest capital city in Europe, tucked in the Pyrenees at 1,023 m.' },
  { name: 'Reykjavik, Iceland', lat: 64.1466, lng: -21.9426, country: 'Iceland', continent: 'Europe', diff: 2, fact: 'The world\'s northernmost capital is heated almost entirely by geothermal energy.' },
  { name: 'Porto, Portugal', lat: 41.1579, lng: -8.6291, country: 'Portugal', continent: 'Europe', diff: 2, fact: 'Port wine ages in cellars across the river in Vila Nova de Gaia.' },
  { name: 'Loch Ness, Scotland', lat: 57.3229, lng: -4.4244, country: 'United Kingdom', continent: 'Europe', diff: 2, fact: 'It holds more fresh water than all the lakes of England and Wales combined.' },
  { name: 'Pompeii', lat: 40.7462, lng: 14.4989, country: 'Italy', continent: 'Europe', diff: 2, fact: 'Volcanic ash preserved loaves of bread still sitting in Roman ovens.' },
  { name: 'Verona Arena', lat: 45.4384, lng: 10.9916, country: 'Italy', continent: 'Europe', diff: 3, fact: 'This Roman amphitheatre still stages open-air opera every summer.' },
  { name: 'Rock of Cashel, Ireland', lat: 52.5199, lng: -7.8907, country: 'Ireland', continent: 'Europe', diff: 3, fact: 'Legend says the rock landed here when the devil took a bite of a mountain.' },
  { name: 'Monaco — Monte Carlo', lat: 43.7396, lng: 7.4272, country: 'Monaco', continent: 'Europe', diff: 2, fact: 'The whole country is smaller than New York\'s Central Park.' },

  // ================= ASIA =================
  { name: 'Great Wall of China (Badaling)', lat: 40.3542, lng: 116.0, country: 'China', continent: 'Asia', diff: 1, fact: 'All its walls and branches together stretch over 21,000 km.' },
  { name: 'Taj Mahal, Agra', lat: 27.1751, lng: 78.0421, country: 'India', continent: 'Asia', diff: 1, fact: 'A marble tomb built by an emperor for his wife, taking 20,000 workers 22 years.' },
  { name: 'Mount Fuji', lat: 35.3606, lng: 138.7274, country: 'Japan', continent: 'Asia', diff: 1, fact: 'Japan\'s highest peak is an active volcano that last erupted in 1707.' },
  { name: 'Tokyo — Shibuya Crossing', lat: 35.6595, lng: 139.7005, country: 'Japan', continent: 'Asia', diff: 1, fact: 'Up to 3,000 people cross this intersection in a single green light.' },
  { name: 'Petra, Jordan', lat: 30.3285, lng: 35.4444, country: 'Jordan', continent: 'Asia', diff: 1, fact: 'The rose-red city was carved into cliffs by the Nabataeans 2,000 years ago.' },
  { name: 'Angkor Wat, Cambodia', lat: 13.4125, lng: 103.867, country: 'Cambodia', continent: 'Asia', diff: 1, fact: 'The largest religious monument on Earth, appearing on Cambodia\'s flag.' },
  { name: 'Burj Khalifa, Dubai', lat: 25.1972, lng: 55.2744, country: 'United Arab Emirates', continent: 'Asia', diff: 1, fact: 'At 828 m you can watch the sunset twice — once from the ground, again from the top.' },
  { name: 'Mount Everest', lat: 27.9881, lng: 86.925, country: 'Nepal', continent: 'Asia', diff: 1, fact: 'The summit ridge marks the border between Nepal and China.' },
  { name: 'Kyoto — Fushimi Inari Shrine', lat: 34.9671, lng: 135.7727, country: 'Japan', continent: 'Asia', diff: 2, fact: 'About 10,000 vermilion torii gates tunnel up the mountainside.' },
  { name: 'Ha Long Bay, Vietnam', lat: 20.9101, lng: 107.1839, country: 'Vietnam', continent: 'Asia', diff: 2, fact: 'Nearly 2,000 limestone islands rise from its emerald water.' },
  { name: 'Bali — Uluwatu Temple', lat: -8.8291, lng: 115.0849, country: 'Indonesia', continent: 'Asia', diff: 2, fact: 'The clifftop temple\'s resident monkeys are famous for stealing sunglasses.' },
  { name: 'Marina Bay Sands, Singapore', lat: 1.2834, lng: 103.8607, country: 'Singapore', continent: 'Asia', diff: 1, fact: 'A ship-shaped skypark with an infinity pool bridges its three towers.' },
  { name: 'Seoul — Gyeongbokgung Palace', lat: 37.5796, lng: 126.977, country: 'South Korea', continent: 'Asia', diff: 2, fact: 'Palace guards still change shifts in Joseon-era uniforms daily.' },
  { name: 'Bagan, Myanmar', lat: 21.1717, lng: 94.8585, country: 'Myanmar', continent: 'Asia', diff: 3, fact: 'Over 2,000 ancient temples dot this plain — hot-air balloons drift over at dawn.' },
  { name: 'Dead Sea', lat: 31.5, lng: 35.5, country: 'Jordan', continent: 'Asia', diff: 2, fact: 'At 430 m below sea level, its shore is the lowest dry land on Earth.' },
  { name: 'Jerusalem Old City', lat: 31.7767, lng: 35.2345, country: 'Israel', continent: 'Asia', diff: 1, fact: 'One square kilometre holds sites sacred to three world religions.' },
  { name: 'Istanbul — Hagia Sophia', lat: 41.0086, lng: 28.9802, country: 'Turkey', continent: 'Asia', diff: 1, fact: 'It has served as a cathedral, a mosque, a museum, and a mosque again.' },
  { name: 'Cappadocia, Turkey', lat: 38.6431, lng: 34.8289, country: 'Turkey', continent: 'Asia', diff: 2, fact: 'People carved entire underground cities into its soft volcanic rock.' },
  { name: 'Beijing — Forbidden City', lat: 39.9163, lng: 116.3972, country: 'China', continent: 'Asia', diff: 1, fact: 'The imperial palace has 980 buildings and, legend says, 9,999.5 rooms.' },
  { name: 'Shanghai — The Bund', lat: 31.2397, lng: 121.4905, country: 'China', continent: 'Asia', diff: 2, fact: 'Colonial-era banks face a futuristic skyline straight across the river.' },
  { name: 'Hong Kong — Victoria Peak', lat: 22.2758, lng: 114.1455, country: 'China', continent: 'Asia', diff: 1, fact: 'The Peak Tram has climbed the hillside since 1888.' },
  { name: 'Zhangjiajie Pillars', lat: 29.3153, lng: 110.4344, country: 'China', continent: 'Asia', diff: 3, fact: 'These quartzite spires inspired the floating mountains in Avatar.' },
  { name: 'Mount Bromo, Indonesia', lat: -7.9425, lng: 112.953, country: 'Indonesia', continent: 'Asia', diff: 3, fact: 'An active crater within an ancient caldera, smoking over a sea of sand.' },
  { name: 'Kathmandu — Boudhanath Stupa', lat: 27.7215, lng: 85.3620, country: 'Nepal', continent: 'Asia', diff: 2, fact: 'The giant stupa\'s painted eyes watch over the city in four directions.' },
  { name: 'Varanasi Ghats, India', lat: 25.3176, lng: 83.0064, country: 'India', continent: 'Asia', diff: 2, fact: 'One of the world\'s oldest living cities, on the banks of the Ganges.' },
  { name: 'Jaipur — Hawa Mahal', lat: 26.9239, lng: 75.8267, country: 'India', continent: 'Asia', diff: 2, fact: 'The "Palace of Winds" has 953 tiny windows and is just one room deep.' },
  { name: 'Maldives — Malé', lat: 4.1755, lng: 73.5093, country: 'Maldives', continent: 'Asia', diff: 2, fact: 'The flattest country on Earth — its highest natural point is under 3 metres.' },
  { name: 'Sri Lanka — Sigiriya Rock', lat: 7.957, lng: 80.7603, country: 'Sri Lanka', continent: 'Asia', diff: 3, fact: 'A 5th-century king built his palace on top of this 200-metre rock column.' },
  { name: 'Bangkok — Grand Palace', lat: 13.75, lng: 100.4913, country: 'Thailand', continent: 'Asia', diff: 1, fact: 'The Emerald Buddha inside is dressed in gold robes changed with the seasons.' },
  { name: 'Phuket, Thailand', lat: 7.8804, lng: 98.3923, country: 'Thailand', continent: 'Asia', diff: 2, fact: 'Thailand\'s largest island sits in the Andaman Sea.' },
  { name: 'Manila, Philippines', lat: 14.5995, lng: 120.9842, country: 'Philippines', continent: 'Asia', diff: 2, fact: 'Its walled district Intramuros dates to the Spanish era of the 1570s.' },
  { name: 'Chocolate Hills, Bohol', lat: 9.8299, lng: 124.1435, country: 'Philippines', continent: 'Asia', diff: 3, fact: 'Over 1,200 grassy mounds turn brown in the dry season — hence the name.' },
  { name: 'Samarkand — Registan', lat: 39.6542, lng: 66.9758, country: 'Uzbekistan', continent: 'Asia', diff: 3, fact: 'A Silk Road crossroads framed by three dazzling tiled madrasas.' },
  { name: 'Almaty, Kazakhstan', lat: 43.222, lng: 76.8512, country: 'Kazakhstan', continent: 'Asia', diff: 3, fact: 'Its name comes from the wild apples that first grew in these mountains.' },
  { name: 'Ulaanbaatar, Mongolia', lat: 47.8864, lng: 106.9057, country: 'Mongolia', continent: 'Asia', diff: 3, fact: 'The coldest capital city on Earth, averaging below freezing year-round.' },
  { name: 'Lake Baikal, Siberia', lat: 53.5587, lng: 108.165, country: 'Russia', continent: 'Asia', diff: 2, fact: 'The deepest lake on Earth holds a fifth of all unfrozen fresh water.' },
  { name: 'Kamchatka Peninsula', lat: 56.1327, lng: 159.5331, country: 'Russia', continent: 'Asia', diff: 3, fact: 'This remote peninsula has about 300 volcanoes, dozens of them active.' },
  { name: 'Riyadh, Saudi Arabia', lat: 24.7136, lng: 46.6753, country: 'Saudi Arabia', continent: 'Asia', diff: 2, fact: 'The desert capital has grown from mud-walled town to 7 million people in 70 years.' },
  { name: 'Doha, Qatar', lat: 25.2854, lng: 51.531, country: 'Qatar', continent: 'Asia', diff: 2, fact: 'Its skyline rose almost entirely after the year 2000.' },
  { name: 'Muscat, Oman', lat: 23.588, lng: 58.3829, country: 'Oman', continent: 'Asia', diff: 3, fact: 'By law, buildings keep traditional style — few towers, lots of white.' },
  { name: 'Baku, Azerbaijan', lat: 40.4093, lng: 49.8671, country: 'Azerbaijan', continent: 'Asia', diff: 3, fact: 'The lowest-lying capital in the world, 28 m below sea level by the Caspian.' },
  { name: 'Tbilisi, Georgia', lat: 41.7151, lng: 44.8271, country: 'Georgia', continent: 'Asia', diff: 3, fact: 'Its name comes from warm sulfur springs — "tbili" means warm.' },
  { name: 'Kuala Lumpur — Petronas Towers', lat: 3.1579, lng: 101.7116, country: 'Malaysia', continent: 'Asia', diff: 1, fact: 'The twin towers were the world\'s tallest buildings from 1998 to 2004.' },
  { name: 'Taipei 101', lat: 25.0339, lng: 121.5645, country: 'Taiwan', continent: 'Asia', diff: 2, fact: 'A 660-tonne golden ball inside sways to steady the tower in typhoons.' },
  { name: 'Kyrgyzstan — Issyk-Kul Lake', lat: 42.44, lng: 77.25, country: 'Kyrgyzstan', continent: 'Asia', diff: 3, fact: 'A mountain lake so large and salty it never freezes, even at 1,600 m.' },

  // ================= NORTH AMERICA =================
  { name: 'Statue of Liberty, New York', lat: 40.6892, lng: -74.0445, country: 'United States of America', continent: 'North America', diff: 1, fact: 'France shipped her across the Atlantic in 350 pieces packed in 214 crates.' },
  { name: 'Grand Canyon', lat: 36.1069, lng: -112.1129, country: 'United States of America', continent: 'North America', diff: 1, fact: 'The Colorado River took about 6 million years to carve it a mile deep.' },
  { name: 'Golden Gate Bridge', lat: 37.8199, lng: -122.4783, country: 'United States of America', continent: 'North America', diff: 1, fact: 'Its color is officially called "International Orange".' },
  { name: 'Niagara Falls', lat: 43.0962, lng: -79.0377, country: 'Canada', continent: 'North America', diff: 1, fact: 'Enough water pours over every second to fill an Olympic pool.' },
  { name: 'Times Square, New York', lat: 40.758, lng: -73.9855, country: 'United States of America', continent: 'North America', diff: 1, fact: 'Around 50 million people pass through it every year.' },
  { name: 'Chichén Itzá, Mexico', lat: 20.6843, lng: -88.5678, country: 'Mexico', continent: 'North America', diff: 1, fact: 'At the equinox, a shadow serpent slithers down the pyramid\'s staircase.' },
  { name: 'Banff — Lake Louise', lat: 51.4254, lng: -116.1773, country: 'Canada', continent: 'North America', diff: 2, fact: 'Glacier flour suspended in the water gives it that impossible turquoise.' },
  { name: 'Yellowstone — Old Faithful', lat: 44.4605, lng: -110.8281, country: 'United States of America', continent: 'North America', diff: 2, fact: 'The world\'s first national park sits atop a supervolcano.' },
  { name: 'Las Vegas Strip', lat: 36.1147, lng: -115.1728, country: 'United States of America', continent: 'North America', diff: 1, fact: 'The Strip is technically outside Las Vegas city limits, in Paradise, Nevada.' },
  { name: 'Hollywood Sign, Los Angeles', lat: 34.1341, lng: -118.3215, country: 'United States of America', continent: 'North America', diff: 1, fact: 'It originally read "HOLLYWOODLAND", advertising a housing development.' },
  { name: 'Mount Rushmore', lat: 43.8791, lng: -103.4591, country: 'United States of America', continent: 'North America', diff: 2, fact: 'Workers removed 450,000 tonnes of granite; no one died during carving.' },
  { name: 'Havana, Cuba', lat: 23.1136, lng: -82.3666, country: 'Cuba', continent: 'North America', diff: 2, fact: 'An estimated 60,000 classic American cars still cruise its streets.' },
  { name: 'Mexico City — Zócalo', lat: 19.4326, lng: -99.1332, country: 'Mexico', continent: 'North America', diff: 1, fact: 'The megacity is slowly sinking into the drained lakebed it was built on.' },
  { name: 'Teotihuacan Pyramids', lat: 19.6925, lng: -98.8438, country: 'Mexico', continent: 'North America', diff: 2, fact: 'The Aztecs found this city already ancient and named it "birthplace of the gods".' },
  { name: 'Chicago — The Bean', lat: 41.8827, lng: -87.6233, country: 'United States of America', continent: 'North America', diff: 1, fact: 'Cloud Gate\'s 168 steel plates are polished so smoothly no seams show.' },
  { name: 'Miami Beach', lat: 25.7907, lng: -80.13, country: 'United States of America', continent: 'North America', diff: 1, fact: 'Its pastel Art Deco district has the world\'s largest collection of 1930s architecture.' },
  { name: 'New Orleans French Quarter', lat: 29.9584, lng: -90.0644, country: 'United States of America', continent: 'North America', diff: 2, fact: 'Most of its famous "French" architecture is actually Spanish colonial.' },
  { name: 'Washington — The Capitol', lat: 38.8899, lng: -77.0091, country: 'United States of America', continent: 'North America', diff: 1, fact: 'A 6-metre bronze Statue of Freedom has topped the dome since 1863.' },
  { name: 'Seattle — Space Needle', lat: 47.6205, lng: -122.3493, country: 'United States of America', continent: 'North America', diff: 2, fact: 'Built for the 1962 World\'s Fair in just 400 days.' },
  { name: 'Denali, Alaska', lat: 63.0692, lng: -151.007, country: 'United States of America', continent: 'North America', diff: 2, fact: 'North America\'s highest peak rises 5,500 m from base to summit — more than Everest.' },
  { name: 'Hawaii — Waikiki Beach', lat: 21.2793, lng: -157.8292, country: 'United States of America', continent: 'North America', diff: 1, fact: 'Surfing was popularized here by Olympic swimmer Duke Kahanamoku.' },
  { name: 'Toronto — CN Tower', lat: 43.6426, lng: -79.3871, country: 'Canada', continent: 'North America', diff: 1, fact: 'You can walk hands-free around the outside edge, 356 m up.' },
  { name: 'Vancouver, Canada', lat: 49.2827, lng: -123.1207, country: 'Canada', continent: 'North America', diff: 2, fact: 'You can ski a mountain and kayak the ocean here on the same day.' },
  { name: 'Quebec City', lat: 46.8131, lng: -71.2075, country: 'Canada', continent: 'North America', diff: 2, fact: 'North America\'s only walled city north of Mexico.' },
  { name: 'Panama Canal', lat: 9.08, lng: -79.68, country: 'Panama', continent: 'North America', diff: 2, fact: 'Ships are lifted 26 m over the continental divide in giant water elevators.' },
  { name: 'Costa Rica — Arenal Volcano', lat: 10.4626, lng: -84.7032, country: 'Costa Rica', continent: 'North America', diff: 3, fact: 'A near-perfect cone that was thought extinct until it erupted in 1968.' },
  { name: 'Tulum, Mexico', lat: 20.2114, lng: -87.4654, country: 'Mexico', continent: 'North America', diff: 2, fact: 'The only major Maya city built right on the Caribbean coast.' },
  { name: 'Nassau, Bahamas', lat: 25.0443, lng: -77.3504, country: 'Bahamas', continent: 'North America', diff: 3, fact: 'Blackbeard the pirate once made this harbor his base.' },
  { name: 'San Juan, Puerto Rico', lat: 18.4655, lng: -66.1057, country: 'United States of America', continent: 'North America', diff: 3, fact: 'Its 16th-century fort El Morro repelled Sir Francis Drake.' },
  { name: 'Guatemala — Tikal', lat: 17.2222, lng: -89.6233, country: 'Guatemala', continent: 'North America', diff: 3, fact: 'Maya temples poke above the rainforest canopy — one starred in Star Wars.' },
  { name: 'Antigua Guatemala', lat: 14.5586, lng: -90.7295, country: 'Guatemala', continent: 'North America', diff: 3, fact: 'Three volcanoes loom over this colonial town of pastel ruins.' },
  { name: 'Jamaica — Montego Bay', lat: 18.4762, lng: -77.8939, country: 'Jamaica', continent: 'North America', diff: 3, fact: 'Its Doctor\'s Cave Beach was famed for supposedly curative waters.' },
  { name: 'Greenland — Nuuk', lat: 64.1836, lng: -51.7214, country: 'Greenland', continent: 'North America', diff: 3, fact: 'One of the world\'s smallest capitals, home to a third of all Greenlanders.' },
  { name: 'Bermuda', lat: 32.3078, lng: -64.7505, country: 'United Kingdom', continent: 'North America', diff: 3, fact: 'Its pink-sand beaches get their color from crushed red coral organisms.' },
  { name: 'St. Louis — Gateway Arch', lat: 38.6247, lng: -90.1848, country: 'United States of America', continent: 'North America', diff: 2, fact: 'At 192 m it is the tallest arch in the world — and it sways in the wind.' },
  { name: 'Nashville, Tennessee', lat: 36.1627, lng: -86.7816, country: 'United States of America', continent: 'North America', diff: 2, fact: 'Music City has a full-scale replica of the Parthenon.' },

  // ================= SOUTH AMERICA =================
  { name: 'Machu Picchu, Peru', lat: -13.1631, lng: -72.545, country: 'Peru', continent: 'South America', diff: 1, fact: 'The Inca citadel was built without wheels, iron tools, or mortar.' },
  { name: 'Christ the Redeemer, Rio', lat: -22.9519, lng: -43.2105, country: 'Brazil', continent: 'South America', diff: 1, fact: 'The 30-metre statue is struck by lightning several times a year.' },
  { name: 'Iguazu Falls', lat: -25.6953, lng: -54.4367, country: 'Argentina', continent: 'South America', diff: 2, fact: 'Its 275 falls make Niagara look, as Eleanor Roosevelt said, "poor".' },
  { name: 'Galápagos Islands', lat: -0.7393, lng: -90.3312, country: 'Ecuador', continent: 'South America', diff: 2, fact: 'Darwin\'s visit here in 1835 helped spark the theory of evolution.' },
  { name: 'Salar de Uyuni, Bolivia', lat: -20.1338, lng: -67.4891, country: 'Bolivia', continent: 'South America', diff: 2, fact: 'After rain, the world\'s largest salt flat becomes a giant mirror of the sky.' },
  { name: 'Buenos Aires — Obelisco', lat: -34.6037, lng: -58.3816, country: 'Argentina', continent: 'South America', diff: 1, fact: 'The city has more bookstores per person than any other in the world.' },
  { name: 'Patagonia — Torres del Paine', lat: -50.9423, lng: -73.4068, country: 'Chile', continent: 'South America', diff: 2, fact: 'Three granite towers rise like blades above turquoise glacial lakes.' },
  { name: 'Atacama Desert', lat: -23.8634, lng: -69.1328, country: 'Chile', continent: 'South America', diff: 3, fact: 'Some weather stations here have never recorded rain.' },
  { name: 'Angel Falls, Venezuela', lat: 5.9701, lng: -62.5362, country: 'Venezuela', continent: 'South America', diff: 2, fact: 'The world\'s tallest waterfall drops 979 m — water turns to mist before landing.' },
  { name: 'Cartagena, Colombia', lat: 10.391, lng: -75.4794, country: 'Colombia', continent: 'South America', diff: 2, fact: 'Its massive stone walls repelled pirates for three centuries.' },
  { name: 'Bogotá, Colombia', lat: 4.711, lng: -74.0721, country: 'Colombia', continent: 'South America', diff: 2, fact: 'One of the highest big cities on Earth, at 2,640 m in the Andes.' },
  { name: 'Amazon River mouth, Brazil', lat: -0.05, lng: -50.5, country: 'Brazil', continent: 'South America', diff: 3, fact: 'The river pushes fresh water 160 km out into the Atlantic.' },
  { name: 'Easter Island (Rapa Nui)', lat: -27.1127, lng: -109.3497, country: 'Chile', continent: 'Oceania', diff: 2, fact: 'Nearly 900 moai statues were carved here; many were "walked" upright to their platforms.' },
  { name: 'Lima, Peru', lat: -12.0464, lng: -77.0428, country: 'Peru', continent: 'South America', diff: 2, fact: 'The desert capital gets less rain than the Sahara but sits on the ocean.' },
  { name: 'Cusco, Peru', lat: -13.5319, lng: -71.9675, country: 'Peru', continent: 'South America', diff: 2, fact: 'Inca stone walls here fit so tightly a credit card can\'t slide between blocks.' },
  { name: 'La Paz, Bolivia', lat: -16.4897, lng: -68.1193, country: 'Bolivia', continent: 'South America', diff: 2, fact: 'The world\'s highest big city commutes by a network of cable cars.' },
  { name: 'Quito, Ecuador', lat: -0.1807, lng: -78.4678, country: 'Ecuador', continent: 'South America', diff: 2, fact: 'It sits practically on the equator — you can stand in both hemispheres nearby.' },
  { name: 'Montevideo, Uruguay', lat: -34.9011, lng: -56.1645, country: 'Uruguay', continent: 'South America', diff: 3, fact: 'Its 22-km beachfront promenade, the Rambla, is among the world\'s longest.' },
  { name: 'Asunción, Paraguay', lat: -25.2637, lng: -57.5759, country: 'Paraguay', continent: 'South America', diff: 3, fact: 'One of South America\'s oldest cities, founded in 1537.' },
  { name: 'São Paulo, Brazil', lat: -23.5505, lng: -46.6333, country: 'Brazil', continent: 'South America', diff: 2, fact: 'The largest city in the Americas banned outdoor advertising in 2007.' },
  { name: 'Fernando de Noronha', lat: -3.8536, lng: -32.4297, country: 'Brazil', continent: 'South America', diff: 3, fact: 'A volcanic archipelago where spinner dolphins gather by the hundreds.' },
  { name: 'Ushuaia, Argentina', lat: -54.8019, lng: -68.303, country: 'Argentina', continent: 'South America', diff: 3, fact: 'The southernmost city in the world — the gateway to Antarctica.' },

  // ================= AFRICA =================
  { name: 'Pyramids of Giza', lat: 29.9792, lng: 31.1342, country: 'Egypt', continent: 'Africa', diff: 1, fact: 'The Great Pyramid was the tallest structure on Earth for 3,800 years.' },
  { name: 'Victoria Falls', lat: -17.9243, lng: 25.8572, country: 'Zambia', continent: 'Africa', diff: 2, fact: 'Locals call it "the smoke that thunders" — spray is visible 50 km away.' },
  { name: 'Table Mountain, Cape Town', lat: -33.9628, lng: 18.4098, country: 'South Africa', continent: 'Africa', diff: 1, fact: 'Its flat top hosts more plant species than the entire United Kingdom.' },
  { name: 'Mount Kilimanjaro', lat: -3.0674, lng: 37.3556, country: 'Tanzania', continent: 'Africa', diff: 1, fact: 'Africa\'s highest peak is a free-standing volcano you can walk up without ropes.' },
  { name: 'Serengeti Plains', lat: -2.3333, lng: 34.8333, country: 'Tanzania', continent: 'Africa', diff: 2, fact: 'Over a million wildebeest migrate across it in a great loop each year.' },
  { name: 'Marrakech — Jemaa el-Fnaa', lat: 31.6258, lng: -7.9891, country: 'Morocco', continent: 'Africa', diff: 1, fact: 'The medina square fills nightly with storytellers, musicians, and food stalls.' },
  { name: 'Sahara — Erg Chebbi, Morocco', lat: 31.1499, lng: -3.9772, country: 'Morocco', continent: 'Africa', diff: 3, fact: 'These dunes rise up to 150 m — camels remain the best way in.' },
  { name: 'Cairo — Khan el-Khalili', lat: 30.0477, lng: 31.2623, country: 'Egypt', continent: 'Africa', diff: 2, fact: 'This bazaar has been trading continuously since 1382.' },
  { name: 'Luxor — Karnak Temple', lat: 25.7188, lng: 32.6573, country: 'Egypt', continent: 'Africa', diff: 2, fact: 'Its great hall of 134 giant columns could hold Notre-Dame cathedral.' },
  { name: 'Zanzibar — Stone Town', lat: -6.1622, lng: 39.1921, country: 'Tanzania', continent: 'Africa', diff: 2, fact: 'The spice island\'s carved wooden doors number in the hundreds.' },
  { name: 'Okavango Delta, Botswana', lat: -19.2833, lng: 22.9, country: 'Botswana', continent: 'Africa', diff: 3, fact: 'A river that never reaches the sea — it fans out and vanishes into the Kalahari.' },
  { name: 'Namib Desert — Sossusvlei', lat: -24.7333, lng: 15.3333, country: 'Namibia', continent: 'Africa', diff: 3, fact: 'Some of the world\'s tallest dunes surround a white clay pan of dead trees.' },
  { name: 'Lagos, Nigeria', lat: 6.5244, lng: 3.3792, country: 'Nigeria', continent: 'Africa', diff: 2, fact: 'Africa\'s biggest metropolis grows by an estimated 3,000 people per day.' },
  { name: 'Nairobi, Kenya', lat: -1.2921, lng: 36.8219, country: 'Kenya', continent: 'Africa', diff: 2, fact: 'The only capital with a national park — lions live within sight of skyscrapers.' },
  { name: 'Maasai Mara, Kenya', lat: -1.4931, lng: 35.1439, country: 'Kenya', continent: 'Africa', diff: 3, fact: 'Named for the Maasai people and the dotted acacia trees — "mara" means spotted.' },
  { name: 'Addis Ababa, Ethiopia', lat: 9.0054, lng: 38.7636, country: 'Ethiopia', continent: 'Africa', diff: 3, fact: 'Africa\'s diplomatic capital sits at a lung-testing 2,355 metres.' },
  { name: 'Lalibela Rock Churches', lat: 12.0317, lng: 39.0411, country: 'Ethiopia', continent: 'Africa', diff: 3, fact: 'Eleven medieval churches carved downward into solid volcanic rock.' },
  { name: 'Timbuktu, Mali', lat: 16.7666, lng: -3.0026, country: 'Mali', continent: 'Africa', diff: 3, fact: 'A byword for "the middle of nowhere" that was once a golden center of learning.' },
  { name: 'Dakar, Senegal', lat: 14.7167, lng: -17.4677, country: 'Senegal', continent: 'Africa', diff: 3, fact: 'Mainland Africa\'s westernmost city, on the Cap-Vert peninsula.' },
  { name: 'Accra, Ghana', lat: 5.6037, lng: -0.187, country: 'Ghana', continent: 'Africa', diff: 3, fact: 'Its coffin makers craft caskets shaped like fish, planes, and chili peppers.' },
  { name: 'Tunis — Carthage', lat: 36.8529, lng: 10.3233, country: 'Tunisia', continent: 'Africa', diff: 3, fact: 'Rome\'s great rival was destroyed in 146 BC — then rebuilt as a Roman city.' },
  { name: 'Algiers, Algeria', lat: 36.7538, lng: 3.0588, country: 'Algeria', continent: 'Africa', diff: 3, fact: 'Capital of Africa\'s largest country, which is 80% Sahara.' },
  { name: 'Madagascar — Avenue of the Baobabs', lat: -20.2508, lng: 44.4183, country: 'Madagascar', continent: 'Africa', diff: 2, fact: 'Some of these bottle-shaped giants are over 800 years old.' },
  { name: 'Seychelles — Mahé', lat: -4.6796, lng: 55.492, country: 'Seychelles', continent: 'Africa', diff: 3, fact: 'Home of the coco de mer, the largest seed in the plant kingdom.' },
  { name: 'Mauritius', lat: -20.3484, lng: 57.5522, country: 'Mauritius', continent: 'Africa', diff: 3, fact: 'The only known home of the dodo, gone within a century of humans arriving.' },
  { name: 'Johannesburg, South Africa', lat: -26.2041, lng: 28.0473, country: 'South Africa', continent: 'Africa', diff: 2, fact: 'The world\'s largest city not built on a river, lake, or coastline — it grew on gold.' },
  { name: 'Kruger National Park', lat: -23.9884, lng: 31.5547, country: 'South Africa', continent: 'Africa', diff: 3, fact: 'Nearly the size of Belgium, with all of the Big Five inside.' },
  { name: 'Rwanda — Volcanoes National Park', lat: -1.4653, lng: 29.5228, country: 'Rwanda', continent: 'Africa', diff: 3, fact: 'Mountain gorillas live on these misty volcano slopes, as studied by Dian Fossey.' },
  { name: 'Djenné Great Mosque, Mali', lat: 13.9053, lng: -4.5555, country: 'Mali', continent: 'Africa', diff: 3, fact: 'The world\'s largest mud-brick building is re-plastered by the whole town yearly.' },
  { name: 'Aswan — Abu Simbel', lat: 22.3372, lng: 31.6258, country: 'Egypt', continent: 'Africa', diff: 3, fact: 'The entire temple was sawn into blocks and moved uphill to escape a reservoir.' },

  // ================= OCEANIA =================
  { name: 'Sydney Opera House', lat: -33.8568, lng: 151.2153, country: 'Australia', continent: 'Oceania', diff: 1, fact: 'Its roof holds over a million self-cleaning ceramic tiles.' },
  { name: 'Great Barrier Reef', lat: -18.2871, lng: 147.6992, country: 'Australia', continent: 'Oceania', diff: 1, fact: 'The only living structure visible from space, built by billions of tiny polyps.' },
  { name: 'Uluru (Ayers Rock)', lat: -25.3444, lng: 131.0369, country: 'Australia', continent: 'Oceania', diff: 1, fact: 'Most of this sandstone giant lies underground, like an iceberg.' },
  { name: 'Melbourne, Australia', lat: -37.8136, lng: 144.9631, country: 'Australia', continent: 'Oceania', diff: 2, fact: 'Famous for having four seasons in one day — pack for all of them.' },
  { name: 'Bondi Beach, Sydney', lat: -33.8908, lng: 151.2743, country: 'Australia', continent: 'Oceania', diff: 2, fact: 'Its seawater pool, the Icebergs, hosts swimmers all winter.' },
  { name: 'Queenstown, New Zealand', lat: -45.0312, lng: 168.6626, country: 'New Zealand', continent: 'Oceania', diff: 2, fact: 'The birthplace of commercial bungee jumping, in 1988.' },
  { name: 'Milford Sound, New Zealand', lat: -44.6717, lng: 167.9256, country: 'New Zealand', continent: 'Oceania', diff: 2, fact: 'Rudyard Kipling called this fjord the eighth wonder of the world.' },
  { name: 'Auckland, New Zealand', lat: -36.8509, lng: 174.7645, country: 'New Zealand', continent: 'Oceania', diff: 2, fact: 'The "City of Sails" is built on a field of about 50 dormant volcanoes.' },
  { name: 'Rotorua, New Zealand', lat: -38.1368, lng: 176.2497, country: 'New Zealand', continent: 'Oceania', diff: 3, fact: 'Geysers and boiling mud pools give the town a permanent sulfur scent.' },
  { name: 'Fiji — Nadi', lat: -17.7765, lng: 177.4356, country: 'Fiji', continent: 'Oceania', diff: 3, fact: 'An archipelago of 333 islands — about a third of them inhabited.' },
  { name: 'Bora Bora', lat: -16.5004, lng: -151.7415, country: 'France', continent: 'Oceania', diff: 2, fact: 'Its lagoon\'s overwater bungalows started a global resort trend in the 1960s.' },
  { name: 'Tahiti — Papeete', lat: -17.5516, lng: -149.5585, country: 'France', continent: 'Oceania', diff: 3, fact: 'Gauguin sailed here in 1891 looking for an untouched paradise to paint.' },
  { name: 'Papua New Guinea — Port Moresby', lat: -9.4438, lng: 147.1803, country: 'Papua New Guinea', continent: 'Oceania', diff: 3, fact: 'PNG\'s people speak over 800 languages — the most of any country.' },
  { name: 'Palau — Rock Islands', lat: 7.2257, lng: 134.3622, country: 'Palau', continent: 'Oceania', diff: 3, fact: 'A lake here holds millions of golden jellyfish that have lost their sting.' },
  { name: 'Great Ocean Road — Twelve Apostles', lat: -38.6621, lng: 143.1051, country: 'Australia', continent: 'Oceania', diff: 3, fact: 'Only eight of the limestone "apostles" still stand against the waves.' },
  { name: 'Tasmania — Hobart', lat: -42.8821, lng: 147.3272, country: 'Australia', continent: 'Oceania', diff: 3, fact: 'Australia\'s island state has some of the cleanest air ever measured.' },
  { name: 'Perth, Australia', lat: -31.9505, lng: 115.8605, country: 'Australia', continent: 'Oceania', diff: 2, fact: 'One of the most isolated big cities on Earth — its nearest peer is 2,100 km away.' },

  // ================= WILDCARDS / REMOTE =================
  { name: 'Antarctica — McMurdo Station', lat: -77.8419, lng: 166.6863, country: null, continent: 'Antarctica', diff: 3, fact: 'The largest Antarctic base houses up to 1,200 people in summer.' },
  { name: 'Svalbard — Longyearbyen', lat: 78.2232, lng: 15.6267, country: 'Norway', continent: 'Europe', diff: 3, fact: 'Home to the Global Seed Vault, a frozen backup of the world\'s crops.' },
  { name: 'Azores — Ponta Delgada', lat: 37.7412, lng: -25.6756, country: 'Portugal', continent: 'Europe', diff: 3, fact: 'These mid-Atlantic volcanic islands sit a thousand miles from the mainland.' },
  { name: 'Canary Islands — Mount Teide', lat: 28.2724, lng: -16.6425, country: 'Spain', continent: 'Africa', diff: 3, fact: 'Spain\'s highest peak is off the coast of Africa, not in Spain proper.' },
  { name: 'Cape Verde — Praia', lat: 14.933, lng: -23.5133, country: 'Cabo Verde', continent: 'Africa', diff: 3, fact: 'An island nation 570 km off West Africa, famous for morna music.' },
  { name: 'Réunion Island', lat: -21.1151, lng: 55.5364, country: 'France', continent: 'Africa', diff: 3, fact: 'One of the world\'s most active volcanoes erupts here almost yearly.' },
  { name: 'Falkland Islands — Stanley', lat: -51.6977, lng: -57.8517, country: 'Falkland Is.', continent: 'South America', diff: 3, fact: 'Penguins outnumber people here by about 200 to 1.' },
  { name: 'Galdhøpiggen, Norway', lat: 61.6363, lng: 8.3126, country: 'Norway', continent: 'Europe', diff: 3, fact: 'Northern Europe\'s highest mountain has a summer ski centre on its glacier.' },
  { name: 'Christmas Island', lat: -10.4475, lng: 105.6904, country: 'Australia', continent: 'Asia', diff: 3, fact: 'Every year tens of millions of red crabs march across it to the sea.' },
  { name: 'Azerbaijan — Yanar Dag', lat: 40.5019, lng: 49.8908, country: 'Azerbaijan', continent: 'Asia', diff: 3, fact: 'A natural gas fire on this hillside has burned continuously for decades.' },
];

// Basic sanity: names must be unique (helps avoid duplicate rounds).
const seen = new Set();
for (const l of LOCATIONS) {
  if (seen.has(l.name)) console.warn('Duplicate location name:', l.name);
  seen.add(l.name);
}
