// MTap background music - original songs synthesized live with WebAudio.
// No audio files, no samples, no licensing questions: every note comes from
// oscillators and noise playing patterns generated by this code.
//
// v3 engine: real song structure (intro -> verse -> build -> DROP -> verse ->
// build -> DROP -> breakdown, 24 bars before repeating), three genres (house /
// rock / metal), and a daily remix - the puzzle number seeds the key, tempo
// feel, chord progression, and rhythm patterns, so every day sounds different.

import { mulberry32 } from './rng.js';

let ctx = null;
let master = null;
let padGain = null;
let schedulerTimer = null;
let nextNoteTime = 0;
let step = 0; // global 16th-note counter
let playing = false;
let padOscs = [];
let currentPadKey = -1;
let song = null; // the composed arrangement for this session

const STEPS_PER_BAR = 16;

const f = (semis) => 440 * Math.pow(2, semis / 12);

// ---- iOS unlock ----
// On iPhone, WebAudio is muted by the physical ring/silent switch (Safari runs it
// in the "ambient" audio session). Playing a looping, silent <audio> element -
// which must start inside a user gesture - flips the session to "playback", after
// which WebAudio (music + sound effects) is audible regardless of the switch.
let unlockEl = null;

function silentWavUrl() {
  const rate = 8000;
  const n = rate;
  const buf = new ArrayBuffer(44 + n * 2);
  const v = new DataView(buf);
  const writeStr = (off, s) => { for (let i = 0; i < s.length; i++) v.setUint8(off + i, s.charCodeAt(i)); };
  writeStr(0, 'RIFF'); v.setUint32(4, 36 + n * 2, true); writeStr(8, 'WAVE');
  writeStr(12, 'fmt '); v.setUint32(16, 16, true); v.setUint16(20, 1, true); v.setUint16(22, 1, true);
  v.setUint32(24, rate, true); v.setUint32(28, rate * 2, true); v.setUint16(32, 2, true); v.setUint16(34, 16, true);
  writeStr(36, 'data'); v.setUint32(40, n * 2, true);
  return URL.createObjectURL(new Blob([buf], { type: 'audio/wav' }));
}

export function unlockIosAudio() {
  try {
    if (!unlockEl) {
      unlockEl = new Audio(silentWavUrl());
      unlockEl.loop = true;
      unlockEl.volume = 0.01;
      unlockEl.setAttribute('playsinline', '');
    }
    const p = unlockEl.play();
    if (p && p.catch) p.catch(() => { /* retried on next gesture */ });
    if (ctx && ctx.state === 'suspended') ctx.resume();
  } catch { /* audio unavailable */ }
}

// ---- audio graph ----

function ensureCtx() {
  if (!ctx) {
    ctx = new (window.AudioContext || window.webkitAudioContext)();
    master = ctx.createGain();
    master.gain.value = 0;
    const comp = ctx.createDynamicsCompressor();
    comp.threshold.value = -18;
    comp.ratio.value = 6;
    master.connect(comp).connect(ctx.destination);
    padGain = ctx.createGain();
    padGain.gain.value = 0.0;
    padGain.connect(master);
  }
  if (ctx.state === 'suspended') ctx.resume();
}

function env(t, attack, peak, decay, dest) {
  const g = ctx.createGain();
  g.gain.setValueAtTime(0.0001, t);
  g.gain.linearRampToValueAtTime(peak, t + attack);
  g.gain.exponentialRampToValueAtTime(0.0001, t + attack + decay);
  g.connect(dest || master);
  return g;
}

const driveCurves = new Map();
function driveCurve(amount) {
  if (!driveCurves.has(amount)) {
    const n = 1024;
    const curve = new Float32Array(n);
    for (let i = 0; i < n; i++) {
      const x = (i / (n - 1)) * 2 - 1;
      curve[i] = Math.tanh(x * amount);
    }
    driveCurves.set(amount, curve);
  }
  return driveCurves.get(amount);
}

// ---- instruments ----

function kick(t, punch = 0.5) {
  const o = ctx.createOscillator();
  o.type = 'sine';
  o.frequency.setValueAtTime(130, t);
  o.frequency.exponentialRampToValueAtTime(42, t + 0.09);
  o.connect(env(t, 0.002, punch, 0.22));
  o.start(t); o.stop(t + 0.3);
  padGain.gain.cancelScheduledValues(t);
  padGain.gain.setValueAtTime(0.05, t);
  padGain.gain.linearRampToValueAtTime(0.28, t + song.stepDur * 3.4);
}

function noiseBurst(t, len, filterType, freq, peak) {
  const buf = ctx.createBuffer(1, Math.max(1, ctx.sampleRate * len), ctx.sampleRate);
  const data = buf.getChannelData(0);
  for (let i = 0; i < data.length; i++) data[i] = (Math.random() * 2 - 1) * (1 - i / data.length);
  const src = ctx.createBufferSource();
  src.buffer = buf;
  const filt = ctx.createBiquadFilter();
  filt.type = filterType;
  filt.frequency.value = freq;
  src.connect(filt).connect(env(t, 0.001, peak, len));
  src.start(t);
}

const clap = (t, g = 0.22) => noiseBurst(t, 0.16, 'bandpass', 1700, g);
const snare = (t, g = 0.2) => { noiseBurst(t, 0.14, 'highpass', 2200, g); kickless(t, 190, 0.12, g * 0.6); };
const hatClosed = (t, g = 0.07) => noiseBurst(t, 0.04, 'highpass', 8500, g);
const hatOpen = (t, g = 0.06) => noiseBurst(t, 0.12, 'highpass', 7500, g);
const crash = (t, g = 0.11) => noiseBurst(t, 0.55, 'highpass', 5200, g);
const impact = (t) => { // the DROP hit: sub boom + crash together
  const o = ctx.createOscillator();
  o.type = 'sine';
  o.frequency.setValueAtTime(72, t);
  o.frequency.exponentialRampToValueAtTime(34, t + 0.4);
  o.connect(env(t, 0.004, 0.55, 0.5));
  o.start(t); o.stop(t + 0.55);
  crash(t, 0.16);
};

function kickless(t, freq, dur, peak) { // tonal thump used inside snare
  const o = ctx.createOscillator();
  o.type = 'triangle';
  o.frequency.value = freq;
  o.connect(env(t, 0.002, peak, dur));
  o.start(t); o.stop(t + dur + 0.05);
}

function bassNote(t, semis, dur, peak, cutoff) {
  const o = ctx.createOscillator();
  o.type = 'sawtooth';
  o.frequency.value = f(semis);
  const lp = ctx.createBiquadFilter();
  lp.type = 'lowpass';
  lp.frequency.setValueAtTime(cutoff, t);
  lp.frequency.exponentialRampToValueAtTime(Math.max(120, cutoff * 0.25), t + dur);
  lp.Q.value = 5;
  o.connect(lp).connect(env(t, 0.004, peak, dur));
  o.start(t); o.stop(t + dur + 0.05);
}

function subNote(t, semis, dur, peak) {
  const o = ctx.createOscillator();
  o.type = 'sine';
  o.frequency.value = f(semis - 12);
  o.connect(env(t, 0.005, peak, dur));
  o.start(t); o.stop(t + dur + 0.05);
}

// Distorted guitar: root + fifth (+octave) saws through a tanh waveshaper.
function guitar(t, semis, dur, drive, peak, cutoff) {
  const shaper = ctx.createWaveShaper();
  shaper.curve = driveCurve(drive);
  const lp = ctx.createBiquadFilter();
  lp.type = 'lowpass';
  lp.frequency.value = cutoff;
  const g = env(t, 0.004, peak, dur);
  shaper.connect(lp).connect(g);
  for (const iv of [0, 7, 12]) {
    const o = ctx.createOscillator();
    o.type = 'sawtooth';
    o.frequency.value = f(semis + iv);
    o.detune.value = iv === 0 ? -4 : 4;
    o.connect(shaper);
    o.start(t); o.stop(t + dur + 0.05);
  }
}

function stab(t, tones, peak) {
  for (const semis of tones) {
    const o = ctx.createOscillator();
    o.type = 'sine';
    o.frequency.value = f(semis);
    o.connect(env(t, 0.004, peak, 0.4));
    o.start(t); o.stop(t + 0.45);
  }
}

function lead(t, semis, peak, bright) {
  const lp = ctx.createBiquadFilter();
  lp.type = 'lowpass';
  lp.frequency.setValueAtTime(bright ? 3400 : 2600, t);
  lp.frequency.exponentialRampToValueAtTime(700, t + 0.14);
  lp.Q.value = 4;
  const g = env(t, 0.004, peak, 0.16);
  lp.connect(g);
  for (const detune of [-6, 6]) {
    const o = ctx.createOscillator();
    o.type = 'sawtooth';
    o.frequency.value = f(semis);
    o.detune.value = detune;
    o.connect(lp);
    o.start(t); o.stop(t + 0.2);
  }
}

function riser(t, dur) {
  const buf = ctx.createBuffer(1, ctx.sampleRate * dur, ctx.sampleRate);
  const data = buf.getChannelData(0);
  for (let i = 0; i < data.length; i++) data[i] = (Math.random() * 2 - 1) * (i / data.length);
  const src = ctx.createBufferSource();
  src.buffer = buf;
  const bp = ctx.createBiquadFilter();
  bp.type = 'bandpass';
  bp.Q.value = 1.5;
  bp.frequency.setValueAtTime(300, t);
  bp.frequency.exponentialRampToValueAtTime(6000, t + dur);
  const g = ctx.createGain();
  g.gain.setValueAtTime(0.0001, t);
  g.gain.linearRampToValueAtTime(0.13, t + dur);
  g.gain.linearRampToValueAtTime(0.0001, t + dur + 0.05);
  src.connect(bp).connect(g).connect(master);
  src.start(t);
}

function padChord(key, tones, t) {
  if (key === currentPadKey) return;
  currentPadKey = key;
  for (const o of padOscs) { try { o.stop(t + 0.05); } catch { /* ok */ } }
  padOscs = [];
  const lp = ctx.createBiquadFilter();
  lp.type = 'lowpass';
  lp.frequency.value = 1100;
  lp.connect(padGain);
  for (const semis of tones) {
    for (const detune of [-7, 7]) {
      const o = ctx.createOscillator();
      o.type = 'sawtooth';
      o.frequency.value = f(semis);
      o.detune.value = detune;
      o.connect(lp);
      o.start(t);
      padOscs.push(o);
    }
  }
}

// ---- composition ----

const QUALITIES = { min: [0, 3, 7], maj: [0, 4, 7], pow: [0, 7, 12] };

const STYLE_DEFS = {
  house: {
    bpm: 126,
    progressions: [
      [{ r: -12, q: 'min' }, { r: -16, q: 'maj' }, { r: -9, q: 'maj' }, { r: -14, q: 'maj' }],
      [{ r: -12, q: 'min' }, { r: -9, q: 'maj' }, { r: -14, q: 'maj' }, { r: -16, q: 'maj' }],
      [{ r: -19, q: 'min' }, { r: -16, q: 'maj' }, { r: -12, q: 'min' }, { r: -14, q: 'maj' }],
    ],
  },
  rock: {
    bpm: 142,
    progressions: [
      [{ r: -17, q: 'pow' }, { r: -14, q: 'pow' }, { r: -19, q: 'pow' }, { r: -12, q: 'pow' }],
      [{ r: -12, q: 'pow' }, { r: -14, q: 'pow' }, { r: -19, q: 'pow' }, { r: -17, q: 'pow' }],
      [{ r: -17, q: 'pow' }, { r: -21, q: 'pow' }, { r: -14, q: 'pow' }, { r: -19, q: 'pow' }],
    ],
  },
  metal: {
    bpm: 158,
    progressions: [
      [{ r: -29, q: 'pow' }, { r: -26, q: 'pow' }, { r: -28, q: 'pow' }, { r: -29, q: 'pow' }],
      [{ r: -29, q: 'pow' }, { r: -31, q: 'pow' }, { r: -26, q: 'pow' }, { r: -28, q: 'pow' }],
      [{ r: -29, q: 'pow' }, { r: -28, q: 'pow' }, { r: -31, q: 'pow' }, { r: -26, q: 'pow' }],
    ],
  },
};

const ARRANGEMENT = [
  { name: 'intro', bars: 2 },
  { name: 'verse', bars: 4 },
  { name: 'build', bars: 2 },
  { name: 'drop', bars: 4 },
  { name: 'verse', bars: 4 },
  { name: 'build', bars: 2 },
  { name: 'drop', bars: 4 },
  { name: 'break', bars: 2 },
]; // 24 bars per pass

function genMask(rng, density) {
  const m = [];
  for (let i = 0; i < 16; i++) m.push(rng() < density ? 1 : 0);
  m[0] = 1; // always land on the downbeat
  return m;
}

function genLeadPattern(rng, density) {
  const p = [];
  for (let i = 0; i < 16; i++) p.push(rng() < density ? Math.floor(rng() * 3) : -1);
  return p;
}

export function composeSong(styleName, daySeed) {
  const def = STYLE_DEFS[styleName] || STYLE_DEFS.house;
  const rng = mulberry32((daySeed * 2654435761 + styleName.length * 97) >>> 0);
  const keyShift = Math.floor(rng() * 5) - 2;                    // -2..+2 semitones
  const bpm = def.bpm + Math.floor(rng() * 9) - 4;               // +/-4 BPM
  const prog = def.progressions[Math.floor(rng() * def.progressions.length)];
  const bars = prog.map((c) => {
    const root = c.r + keyShift;
    const tones = QUALITIES[c.q].map((iv) => root + iv);
    return { root, tones };
  });
  const totalBars = ARRANGEMENT.reduce((a, s) => a + s.bars, 0);
  const sectionAt = [];
  let barCursor = 0;
  for (const s of ARRANGEMENT) {
    for (let b = 0; b < s.bars; b++) sectionAt.push({ name: s.name, barInSection: b, sectionBars: s.bars });
    barCursor += s.bars;
  }
  return {
    style: styleName,
    bpm,
    stepDur: 60 / bpm / 4,
    bars,
    sectionAt,
    totalSteps: totalBars * STEPS_PER_BAR,
    verseLead: genLeadPattern(rng, 0.35),
    dropLead: genLeadPattern(rng, 0.6),
    chugMask: genMask(rng, styleName === 'metal' ? 0.75 : 0.5),
    verseChug: genMask(rng, 0.4),
  };
}

// ---- the scheduler ----

function scheduleStep(globalStep, t) {
  const s = globalStep % song.totalSteps;
  const bar = Math.floor(s / STEPS_PER_BAR);
  const sixteenth = s % STEPS_PER_BAR;
  const sec = song.sectionAt[bar];
  const chord = song.bars[bar % song.bars.length];
  const isLastBuildBar = sec.name === 'build' && sec.barInSection === sec.sectionBars - 1;

  // THE GAP: the last two 16ths before a drop go silent - then the drop slams in.
  if (isLastBuildBar && sixteenth >= 14) return;

  // Section-start punctuation
  if (sixteenth === 0 && sec.barInSection === 0) {
    if (sec.name === 'drop') impact(t);
    else if (sec.name !== 'intro') crash(t, 0.09);
    if (sec.name === 'build') riser(t, song.stepDur * (STEPS_PER_BAR * sec.sectionBars - 2));
  }

  const st = song.style;
  const inGroove = sec.name === 'verse' || sec.name === 'drop' || sec.name === 'build';
  const isDrop = sec.name === 'drop';

  // Pad: house always (ducked by kick); intro/break for all styles.
  if (st === 'house' || sec.name === 'intro' || sec.name === 'break') {
    padChord(bar % song.bars.length, chord.tones, t);
  }

  // Build-section snare roll: density doubles over the last bar.
  if (sec.name === 'build') {
    const rollEvery = isLastBuildBar ? (sixteenth >= 8 ? 1 : 2) : 4;
    if (sixteenth % rollEvery === 0) (st === 'house' ? clap : snare)(t, 0.1 + (sixteenth / 16) * 0.12);
  }

  if (st === 'house') {
    if (inGroove && sixteenth % 4 === 0) kick(t, isDrop ? 0.55 : 0.45);
    if (inGroove && sec.name !== 'build' && (sixteenth === 4 || sixteenth === 12)) clap(t);
    if (inGroove && sixteenth % 4 === 2) bassNote(t, chord.root - 12, 0.18, 0.26, 900);
    if (isDrop && sixteenth % 4 === 0) subNote(t, chord.root - 12, 0.22, 0.3);
    if ((sec.name === 'verse' || isDrop) && (sixteenth === 2 || sixteenth === 6)) stab(t, chord.tones, 0.045);
    if (inGroove && sixteenth % 2 === 1) hatClosed(t, isDrop ? 0.08 : 0.06);
    if (isDrop && sixteenth % 8 === 6) hatOpen(t);
    const pat = isDrop ? song.dropLead : song.verseLead;
    if ((sec.name === 'verse' || isDrop) && pat[sixteenth] >= 0) {
      lead(t, chord.tones[pat[sixteenth]] + (isDrop ? 24 : 12), isDrop ? 0.075 : 0.055, isDrop);
    }
  } else if (st === 'rock') {
    if (inGroove && (sixteenth === 0 || sixteenth === 6 || sixteenth === 8 || sixteenth === 14)) kick(t, 0.5);
    if (inGroove && sec.name !== 'build' && (sixteenth === 4 || sixteenth === 12)) snare(t);
    if (inGroove && sixteenth % 2 === 0) bassNote(t, chord.root - 12, 0.14, 0.22, 600);
    if (sec.name === 'verse' && sixteenth === 0) guitar(t, chord.root, 1.4, 3.5, 0.16, 2800);
    if (isDrop && song.chugMask[sixteenth]) guitar(t, chord.root, 0.11, 5, 0.14, 1100);
    if (isDrop && sixteenth === 0) guitar(t, chord.root, 0.9, 4, 0.15, 3000);
    if (inGroove && sixteenth % 2 === 1) hatClosed(t, 0.05);
    const pat = isDrop ? song.dropLead : song.verseLead;
    if (isDrop && pat[sixteenth] >= 0) lead(t, chord.tones[pat[sixteenth]] + 24, 0.06, true);
  } else { // metal
    const mask = isDrop ? song.chugMask : song.verseChug;
    if (inGroove && mask[sixteenth]) {
      guitar(t, chord.root, 0.09, 7, 0.15, 950);       // palm-mute chug
      kick(t, 0.42);                                    // double-kick shadows the riff
      bassNote(t, chord.root, 0.09, 0.18, 500);
    }
    if (inGroove && sec.name !== 'build' && (sixteenth === 4 || sixteenth === 12)) snare(t, 0.24);
    if (isDrop && sixteenth === 0) guitar(t, chord.root, 1.2, 6, 0.16, 3200); // open ring
    if (inGroove && sixteenth % 4 === 2) hatClosed(t, 0.05);
  }

  // Breakdown: sparse echo of the lead over the pad.
  if (sec.name === 'break' && (sixteenth === 0 || sixteenth === 6 || sixteenth === 10)) {
    lead(t, chord.tones[sixteenth % 3] + 12, 0.05, false);
  }
}

function schedulerTick() {
  while (nextNoteTime < ctx.currentTime + 0.25) {
    scheduleStep(step, nextNoteTime);
    step++;
    nextNoteTime += song.stepDur;
  }
}

// ---- public API ----

export const MUSIC_STYLES = ['house', 'rock', 'metal'];

export function startMusic(styleName = 'house', daySeed = 1) {
  unlockIosAudio();
  ensureCtx();
  if (playing) return;
  playing = true;
  song = composeSong(styleName, daySeed);
  step = 0;
  currentPadKey = -1;
  nextNoteTime = ctx.currentTime + 0.1;
  master.gain.cancelScheduledValues(ctx.currentTime);
  master.gain.setValueAtTime(0.0001, ctx.currentTime);
  master.gain.linearRampToValueAtTime(0.42, ctx.currentTime + 1.2);
  schedulerTimer = setInterval(schedulerTick, 100);
}

export function stopMusic() {
  if (!playing) return;
  playing = false;
  clearInterval(schedulerTimer);
  if (ctx && master) {
    master.gain.cancelScheduledValues(ctx.currentTime);
    master.gain.setValueAtTime(master.gain.value, ctx.currentTime);
    master.gain.linearRampToValueAtTime(0.0001, ctx.currentTime + 0.7);
    const stopAt = ctx.currentTime + 0.8;
    for (const o of padOscs) { try { o.stop(stopAt); } catch { /* ok */ } }
    padOscs = [];
    currentPadKey = -1;
  }
}

export function isMusicPlaying() { return playing; }

// Briefly dip the music so a sound effect (the arrow confirm) cuts through.
export function duckMusic(ms = 400) {
  if (!ctx || !master || !playing) return;
  const t = ctx.currentTime;
  master.gain.cancelScheduledValues(t);
  master.gain.setValueAtTime(master.gain.value, t);
  master.gain.linearRampToValueAtTime(0.1, t + 0.03);
  master.gain.linearRampToValueAtTime(0.42, t + Math.max(0.2, ms / 1000));
}
