// Append-only scheduled news locations. Entries are committed before their day.
import { mulberry32 } from './rng.js';

export const NEWS_START = 44;
export const NEWS = [
  {
    pn: 47,
    slot: 2,
    name: 'Mount Sinabung',
    prompt: 'Volcano erupts for the first time in five years in North Sumatra',
    lat: 3.1696,
    lng: 98.3930,
    country: 'Indonesia',
    continent: 'Asia',
    diff: 2,
    fact: 'Mount Sinabung sent an ash column roughly 3,500 meters above its summit after lying quiet for five years, prompting the evacuation of hundreds of nearby residents.',
  },
  {
    pn: 66,
    slot: 2,
    name: 'Hurricane Polo',
    prompt: "Category 5 hurricane churns off Mexico's Pacific coast",
    lat: 15.3,
    lng: -101.4,
    country: null,
    continent: 'North America',
    diff: 2,
    fact: 'Hurricane Polo rocketed to Category 5 strength with 180 mph winds while stalled off the coast of Zihuatanejo, ranking it among the strongest storms on Earth this year.',
    offshore: true,
  },
  {
    pn: 67,
    slot: 2,
    name: 'Rodanthe, North Carolina',
    prompt: "Powerful nor'easter breaches the Outer Banks' only highway",
    lat: 35.5943,
    lng: -75.4682,
    country: 'United States of America',
    continent: 'North America',
    diff: 2,
    fact: "A strengthening nor'easter drove waves as high as 18 feet into North Carolina's Outer Banks, breaching the dunes and washing out a stretch of Highway 12 near the Pea Island refuge.",
  },
  {
    pn: 69,
    slot: 2,
    name: "Loyalty Islands, New Caledonia",
    prompt: "Strong shallow earthquake shakes New Caledonia's Loyalty Islands",
    lat: -21.298,
    lng: 168.610,
    country: null,
    continent: 'Oceania',
    diff: 2,
    fact: 'A shallow magnitude 6.6 earthquake struck the Pacific seafloor about 68 kilometers east-northeast of Tadine, with officials warning of possible strong currents and unusual surges along nearby shorelines.',
    offshore: true,
  },
  {
    pn: 75,
    slot: 2,
    name: 'Lake Arendsee, Germany',
    prompt: 'Divers pull 10,500-year-old worked timber from a sinking German lake',
    lat: 52.8872,
    lng: 11.4654,
    country: 'Germany',
    continent: 'Europe',
    diff: 2,
    fact: 'Divers recovered carved wooden posts and boards from the bed of Lake Arendsee dated to about 10,500 years ago, among the oldest worked timber found in Germany and evidence of building know-how that predates farming in the region.',
  },
  {
    pn: 76,
    slot: 2,
    name: 'Anak Krakatau, Indonesia',
    prompt: 'New islands emerge after a volcano erupts in the Sunda Strait',
    lat: -6.102,
    lng: 105.423,
    country: null,
    continent: 'Asia',
    diff: 2,
    fact: "Satellite images showed two new islands forming inside the caldera around Anak Krakatau after the volcano's weeks-long eruption sent ash columns miles into the sky and disrupted thousands of flights across Java and Sumatra.",
    offshore: true,
  },
];

export function newsRollFor(pn) {
  return mulberry32(pn * 17 + 3)() < 0.40;
}
